#!/usr/bin/env python3
"""Generate canonical first-slice encounter contracts and executable gate policy."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "content/vertical_slice/slice_001_encounters.json"
POLICY = ROOT / "content/vertical_slice/slice_001_encounter_directors.json"
OUT = ROOT / "verse/bosses/slice_001_encounter_directors.verse"


def q(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def arr(values: list[str]) -> str:
    return "array{" + ", ".join(q(value) for value in values) + "}"


def render() -> str:
    source = json.loads(SOURCE.read_text())
    policies = json.loads(POLICY.read_text())
    bosses = {boss["boss_id"]: boss for boss in source["boss_encounters"]}
    lines = [
        "# GENERATED by tools/build_slice_encounter_directors.py; do not hand edit.",
        "# Canonical source: content/vertical_slice/slice_001_encounters.json",
        "# Gates: content/vertical_slice/slice_001_encounter_directors.json",
        "",
        "Slice001EncounterDirectors:[]aeonfall_encounter_director_contract = array{",
    ]
    for policy in policies["encounters"]:
        boss_kind = policy["kind"] == "Boss"
        authored = bosses[policy["id"]] if boss_kind else source["world_event"]
        phases = authored["phases" if boss_kind else "stages"]
        lines += [
            "    aeonfall_encounter_director_contract{",
            f"        EncounterId := {q(policy['id'])},",
            f"        Kind := aeonfall_encounter_kind.{policy['kind']},",
        ]
        if boss_kind:
            lines += [
                "        BossContract := aeonfall_boss_encounter_contract{",
                f"            BossId := {q(policy['id'])},",
                '            RegionId := "REG-001",',
                f"            MaxConcurrentAdds := {authored['candidate_add_cap']},",
                f"            RewardUnlockIds := {arr(authored['rewards']['unlock_ids'])},",
                "            PhaseContracts := array{",
            ]
            for phase in phases:
                lines += [
                    "                aeonfall_boss_phase_contract{",
                    f"                    PhaseId := {q(phase['id'])},",
                    f"                    DisplayName := {q(phase['name'])},",
                    f"                    ObjectiveIds := {arr(phase['objectives'])},",
                    # Weak points are available vulnerabilities, not mandatory
                    # transition requirements in the authored slice prose.
                    "                    RequiredWeakPointIds := array{},",
                    f"                    ActiveHazardIds := {arr(phase['hazards'])},",
                    f"                    ActiveSpawnGroupIds := {arr(phase['spawn_groups'])},",
                    f"                    AllowsDirectBossDamage := {str(phase['allows_direct_boss_damage']).lower()},",
                    f"                    MaxActiveAdds := {authored['candidate_add_cap']}",
                    "                },",
                ]
            lines += ["            }", "        },"]
        else:
            lines += [
                "        EventContract := aeonfall_world_event_contract{",
                f"            EventId := {q(policy['id'])},",
                "            StageContracts := array{",
            ]
            for phase in phases:
                lines += [
                    "                aeonfall_world_event_stage_contract{",
                    f"                    StageId := {q(phase['id'])},",
                    f"                    DisplayName := {q(phase['name'])},",
                    f"                    RegionIds := {arr(phase['regions'])},",
                    f"                    ObjectiveIds := {arr(phase['objectives'])},",
                    f"                    SpawnGroupIds := {arr(phase['spawn_groups'])},",
                    f"                    HazardIds := {arr(phase['hazards'])},",
                    f"                    EscalatesOnFailure := {str(phase['escalates_on_failure']).lower()},",
                    f"                    MaxConcurrentAi := {authored['candidate_ai_cap']}",
                    "                },",
                ]
            lines += ["            }", "        },"]
        lines += ["        ProgressionPhases := array{"]
        for authored_phase, phase_policy in zip(phases, policy["phases"], strict=True):
            lines += [
                "            aeonfall_encounter_progression_phase{",
                f"                PhaseId := {q(authored_phase['id'])},",
                "                ObjectiveTargets := array{",
            ]
            for objective in authored_phase["objectives"]:
                count = phase_policy["objective_counts"].get(objective, 1)
                lines += [f"                    aeonfall_encounter_counter_contract{{Id := {q(objective)}, RequiredCount := {count}}},"]
            lines += [
                "                },",
                f"                WeakPointIds := {arr(authored_phase.get('weak_points', []))},",
                "                SignalTargets := array{",
            ]
            for signal in phase_policy["signals"]:
                lines += [
                    "                    aeonfall_encounter_counter_contract{"
                    f"Id := {q(signal['id'])}, RequiredCount := {signal['count']}, "
                    f"BossHealthPercent := {signal.get('boss_health_percent', 0)}, "
                    f"BossDefeat := {str(signal.get('boss_defeat', False)).lower()}"
                    "},"
                ]
            lines += ["                },", "                TransitionAlternatives := array{"]
            for gate in phase_policy["transition_alternatives"]:
                lines += [
                    "                    aeonfall_encounter_transition_gate{",
                    f"                        ObjectiveIds := {arr(gate['objectives'])},",
                    f"                        WeakPointIds := {arr(gate['weak_points'])},",
                    f"                        SignalIds := {arr(gate['signals'])}",
                    "                    },",
                ]
            lines += ["                }", "            },"]
        lines += ["        }", "    },"]
    lines += [
        "}",
        "",
        "GetSlice001EncounterDirector(EncounterId:string)<decides><transacts>:aeonfall_encounter_director_contract=",
        "    var Found:?aeonfall_encounter_director_contract = false",
        "    for (Definition : Slice001EncounterDirectors, Definition.EncounterId = EncounterId):",
        "        set Found = option{Definition}",
        "    Found?",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    OUT.write_text(render(), encoding="utf-8")
    print(f"Generated {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
